openapi: 3.0.0
info:
  description: Hello API
  version: "1.0.0"
  title: Hello API
  contact:
    email: davetii@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

servers:
  - url: http://localhost:8080/api
    description: Local Server

paths:
  /v1/hello:
    parameters:
      - in: query
        name: name
        required: true
        schema:
          type: string
    get:
      summary: say hello
      operationId: sayHello
      responses:
        '200':
          description: hello
          content:
            text/plain:
              schema:
                type: string
                example: hello
